# Generated by Django 5.0.2 on 2024-02-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autRecord', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
    ]
